plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/abramson/Library/Mobile Documents/com~apple~CloudDocs/QClaw Workspace/workspace/crm-lite/deploy"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]