/* Мои слова · 我的生词 — v2.0.0
   Разделы (Слова/Фразы/Названия), тэги вместо «пометок», статус Лаоши, версия в шапке. */
const KINDS=[{k:'word',ru:'Слова',zh:'词',forms:['слово','слова','слов']},{k:'phrase',ru:'Фразы',zh:'短语',forms:['фраза','фразы','фраз']},{k:'name',ru:'Названия',zh:'名称',forms:['название','названия','названий']}];
/* слова, которых ещё нет в Лаоши (всё остальное считается внесённым) */
const LAOSHI_NEW=['尽量','澡堂'];
const LAOSHI_SET=new Set(LAOSHI_NEW);
const KMAP={};KINDS.forEach(x=>KMAP[x.k]=x);
function mkBase(r,i){const t=String(r[3]||'').trim();const hz=r[0]||'';return{id:i+1,order:i+1,kind:'word',hanzi:hz,pinyin:r[1]||'',translation:r[2]||'',tags:t?[t]:[],comment:'',laoshi:!LAOSHI_SET.has(String(hz).trim()),favorite:false,createdAt:'',updatedAt:''};}
const BASE_WORDS=(window.CIDIAN_BASE||[]).map(mkBase);
const STORAGE='cidian-data-v1',VERSION='2.1.0',SNAP='cidian-backup-auto',MAX_BYTES=4200000,MIGR_KEY='cidian-migr',MIGR_TAG='laoshi-2026-09-28';
let words=loadWords(),currentTab='words',kind='word',addKind='word',sortMode='order',filter='all',tagFilter=[],query='',visible=120,editingId=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function migrate(w){const o={...w};if(!Array.isArray(o.tags))o.tags=String(o.note||'').trim()?[String(o.note).trim()]:[];o.tags=o.tags.map(t=>String(t).trim()).filter(Boolean);delete o.note;if(o.kind!=='phrase'&&o.kind!=='name')o.kind='word';o.laoshi=!!o.laoshi;o.favorite=!!o.favorite;o.comment=o.comment||'';return o;}
function loadWords(){let arr=null;try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');if(Array.isArray(x)&&x.length)arr=x.map(migrate);}catch(e){}
if(!arr)arr=BASE_WORDS.map(x=>({...x}));
/* одноразовая разметка статуса Лаоши (28.09.2026): всё внесено, кроме 尽量 и 澡堂 */
try{if(localStorage.getItem(MIGR_KEY)!==MIGR_TAG){snapMake('перед разметкой «в Лаоши» (28.09.2026)');arr.forEach(w=>{w.laoshi=!LAOSHI_SET.has(String(w.hanzi).trim());});localStorage.setItem(MIGR_KEY,MIGR_TAG);localStorage.setItem(STORAGE,JSON.stringify(arr));}}catch(e){}
return arr;}
function saveWords(){const blob=JSON.stringify(words);if(blob.length>MAX_BYTES&&!saveWords.warned){saveWords.warned=true;alert('Словарь занимает '+Math.round(blob.length/1024)+' КБ из ~5000 КБ. Сделайте резервную копию (Ещё → Резервная копия): при переполнении браузер может стереть данные.');}try{localStorage.setItem(STORAGE,blob);}catch(e){alert('Не удалось сохранить словарь на устройстве.');}updateCounts();}
function snapInfo(){try{const j=JSON.parse(localStorage.getItem(SNAP)||'null');return j&&j.words?j:null;}catch(e){return null;}}
function snapMake(reason){try{localStorage.setItem(SNAP,JSON.stringify({ts:new Date().toISOString(),reason,words}));}catch(e){}}
function snapDate(ts){try{return new Date(ts).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}catch(e){return ts;}}
function snapRestore(){const j=snapInfo();if(!j)return;if(confirm('Вернуть словарь из автоснимка от '+snapDate(j.ts)+' ('+j.words.length+' записей)? Текущие правки будут заменены.')){snapMake('перед возвратом автоснимка');words=j.words.map(migrate);saveWords();renderMore();}}
function toast(msg,actionLabel,action,doneMsg){const old=document.getElementById('toast');if(old)old.remove();const d=document.createElement('div');d.id='toast';d.className='toast';d.innerHTML='<span>'+esc(msg)+'</span>';const timer=setTimeout(()=>d.remove(),action?7000:3500);if(actionLabel&&action){const b=document.createElement('button');b.className='toast-act';b.textContent=actionLabel;b.onclick=()=>{clearTimeout(timer);d.remove();action();if(doneMsg)toast(doneMsg);};d.appendChild(b);}document.body.appendChild(d);}
function countOf(k){let n=0;for(const w of words)if(w.kind===k)n++;return n;}
function newOf(k){let n=0;for(const w of words)if(w.kind===k&&!w.laoshi)n++;return n;}
function updateCounts(){const el=$('#count');if(el){const m=KMAP[kind]||KMAP.word;el.textContent=countOf(kind).toLocaleString('ru-RU')+' '+pl(countOf(kind),m.forms);}const sc=$('#settingsCount');if(sc)sc.textContent=words.length.toLocaleString('ru-RU');}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function pl(n,f){const a=Math.abs(n)%100,b=a%10;if(a>10&&a<20)return f[2];if(b>1&&b<5)return f[1];if(b===1)return f[0];return f[2];}
function tagPool(){const m=new Map();for(const w of words)for(const t of(w.tags||[]))m.set(t,(m.get(t)||0)+1);return [...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ru'));}
function getFiltered(){let a=words.filter(w=>w.kind===kind);const q=norm(query.trim());if(q)a=a.filter(w=>norm(w.hanzi+' '+w.pinyin+' '+w.translation+' '+w.comment+' '+(w.tags||[]).join(' ')).includes(q));if(filter==='new')a=a.filter(w=>!w.laoshi);if(filter==='done')a=a.filter(w=>w.laoshi);if(tagFilter.length)a=a.filter(w=>(w.tags||[]).some(t=>tagFilter.includes(t)));if(sortMode==='order')a.sort((x,y)=>(x.order||0)-(y.order||0));if(sortMode==='new')a.sort((x,y)=>(y.order||0)-(x.order||0));if(sortMode==='hanzi')a.sort((x,y)=>String(x.hanzi).localeCompare(String(y.hanzi),'zh-CN'));return a;}
function headHtml(){return `<div class="head"><img src="icon-192-v4.png" class="app-icon" alt="词 — Мои слова" width="112" height="112"><div class="headtext"><div class="title-row"><div class="title">Мои слова</div><div class="ver">v${VERSION}</div></div><div class="subtitle">我的生词</div><div class="count" id="count"></div></div></div>`;}
function kindsHtml(){return `<div class="kinds">${KINDS.map(m=>`<button class="kindbtn ${kind===m.k?'on':''}" data-kind="${m.k}"><b>${m.ru} <span class="zh">${m.zh}</span></b><small>${countOf(m.k).toLocaleString('ru-RU')}</small></button>`).join('')}</div>`;}
function tagsBarHtml(){return (tagFilter.length?tagFilter.map(t=>`<button class="chip tag on" data-untag="${esc(t)}">#${esc(t)} ✕</button>`).join(''):'')+`<button class="chip" id="tagBtn"># тэги${tagFilter.length?' ('+tagFilter.length+')':''}</button>`;}
function renderWords(){currentTab='words';setTabs();$('#content').innerHTML=headHtml()+kindsHtml()+`<div class="searchrow"><div class="search"><span class="mag">⌕</span><input id="q" placeholder="Поиск: слово, пиньинь, перевод, тэг" value="${esc(query)}"><button class="clear ${query?'':'hidden'}" id="clearQ" aria-label="Очистить поиск">×</button></div><button class="iconbtn" id="sortBtn" aria-label="Сортировка">☷</button></div><div class="chips"><button class="chip ${filter==='all'?'on':''}" data-f="all">Все</button><button class="chip ${filter==='new'?'on':''}" data-f="new">Не в Лаоши</button><button class="chip ${filter==='done'?'on':''}" data-f="done">В Лаоши</button>${tagsBarHtml()}</div><div id="bulk"></div><div class="list" id="list"></div>`;updateCounts();bindWordControls();renderList();}
function bindWordControls(){$('#q').addEventListener('input',e=>{query=e.target.value;visible=120;$('#clearQ').classList.toggle('hidden',!query);renderList();});$('#clearQ').onclick=()=>{query='';$('#q').value='';$('#clearQ').classList.add('hidden');visible=120;renderList();};$('#sortBtn').onclick=showSort;$$('.chip').forEach(b=>{if(b.dataset.f)b.onclick=()=>{filter=b.dataset.f;visible=120;renderWords();};else if(b.dataset.untag)b.onclick=()=>{tagFilter=tagFilter.filter(t=>t!==b.dataset.untag);visible=120;renderWords();};});const tb=$('#tagBtn');if(tb)tb.onclick=showTags;$$('.kindbtn').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;addKind=kind;visible=120;renderWords();});}
function renderList(){const all=getFiltered(),take=all.slice(0,visible),list=$('#list');const bulk=$('#bulk');if(bulk)bulk.innerHTML=(filter==='new'&&all.length)?`<button class="bulkbar" id="bulkLaoshi">✓ Внести показанные (${all.length.toLocaleString('ru-RU')}) в Лаоши</button>`:'';if(bulk&&$('#bulkLaoshi'))$('#bulkLaoshi').onclick=bulkLaoshi;if(!list)return;if(!take.length){list.innerHTML='<div class="empty">Ничего не найдено</div>';return;}list.innerHTML=take.map(w=>`<div class="word ${w.laoshi?'done':'fresh'}" data-id="${w.id}"><div class="hanzi">${esc(w.hanzi)}</div><div class="meta"><div class="py">${esc(w.pinyin||'')}</div><div class="tr">${esc(w.translation||'')}</div>${(w.tags||[]).map(t=>`<span class="tg" data-tag="${esc(t)}">#${esc(t)}</span>`).join('')}</div><button class="ck ${w.laoshi?'on':''}" data-ck="${w.id}" title="${w.laoshi?'в Лаоши — нажмите, чтобы снять':'не в Лаоши — нажмите, чтобы отметить'}">${w.laoshi?'✓':'○'}</button></div>`).join('')+(all.length>visible?`<button class="more" id="more">Показать ещё · ${all.length-visible}</button>`:'');list.querySelectorAll('.word').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-ck]')||e.target.closest('[data-tag]'))return;openDetail(+el.dataset.id);});list.querySelectorAll('[data-ck]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleLaoshi(+b.dataset.ck,true);});list.querySelectorAll('[data-tag]').forEach(s=>s.onclick=e=>{e.stopPropagation();const t=s.dataset.tag;if(!tagFilter.includes(t))tagFilter.push(t);visible=120;renderWords();});const m=$('#more');if(m)m.onclick=()=>{visible+=150;renderList();};}
function toggleLaoshi(id,quick){const w=words.find(x=>x.id===id);if(!w)return;w.laoshi=!w.laoshi;w.updatedAt=new Date().toISOString();saveWords();if(currentTab==='words'){renderList();}else{openDetail(id);}if(quick)toast(w.laoshi?'В Лаоши: '+w.hanzi:'Снял отметку: '+w.hanzi);}
function bulkLaoshi(){const list=getFiltered();if(!list.length)return;if(!confirm('Отметить «в Лаоши» '+list.length+' записей по текущему отбору?'))return;snapMake('перед отметкой «в Лаоши»');const ids=new Set(list.map(w=>w.id));const before=words.map(w=>({id:w.id,laoshi:w.laoshi}));words.forEach(w=>{if(ids.has(w.id)){w.laoshi=true;w.updatedAt=new Date().toISOString();}});saveWords();filter='all';renderWords();toast('В Лаоши: '+list.length,'Вернуть',()=>{const m=new Map(before.map(b=>[b.id,b.laoshi]));words.forEach(w=>{if(m.has(w.id))w.laoshi=m.get(w.id);});saveWords();renderWords();},'Отметки возвращены');}
function setTabs(){$$('.tab').forEach(x=>x.classList.toggle('on',x.dataset.tab===currentTab));}
function renderAdd(id=null){currentTab='add';editingId=id;setTabs();const w=id?words.find(x=>x.id===id):{hanzi:'',pinyin:'',translation:'',tags:[],comment:'',kind:addKind};if(id&&w)addKind=w.kind;const k=KMAP[addKind]||KMAP.word;$('#content').innerHTML=`<div class="view-title">${id?'Редактировать':'Добавить'}</div><div class="subtitle" style="margin-top:-15px;margin-bottom:14px">${id?'编辑':'新词条'}</div><div class="kinds">${KINDS.map(m=>`<button class="kindbtn ${addKind===m.k?'on':''}" data-akind="${m.k}"><b>${m.ru} <span class="zh">${m.zh}</span></b></button>`).join('')}</div><div class="form"><label>Слово / фраза / название</label><input id="fHanzi" value="${esc(w.hanzi)}" autocomplete="off"><label>Пиньинь</label><input id="fPy" value="${esc(w.pinyin||'')}" autocomplete="off"><label>Перевод</label><textarea id="fTr">${esc(w.translation||'')}</textarea><label>Тэги (через запятую)</label><input id="fTags" value="${esc((w.tags||[]).join(', '))}" placeholder="например: 成语, урок 10" autocomplete="off" list="tagList"><datalist id="tagList">${tagPool().map(t=>`<option value="${esc(t[0])}"></option>`).join('')}</datalist><label>Заметка</label><textarea id="fComment" style="min-height:70px" placeholder="необязательно">${esc(w.comment||'')}</textarea><button class="primary" id="saveBtn">Сохранить в «${k.ru}»</button>${id?'':'<button class="secondary" id="saveNext">Сохранить и добавить следующее</button>'}</div>`;$$('.kindbtn').forEach(b=>b.onclick=()=>{addKind=b.dataset.akind;const h=$('#fHanzi').value,py=$('#fPy').value,tr=$('#fTr').value,tg=$('#fTags').value,cm=$('#fComment').value;renderAdd(id);$('#fHanzi').value=h;$('#fPy').value=py;$('#fTr').value=tr;$('#fTags').value=tg;$('#fComment').value=cm;});$('#saveBtn').onclick=()=>saveForm(false);const sn=$('#saveNext');if(sn)sn.onclick=()=>saveForm(true);}
function parseTags(s){return [...new Set(String(s||'').split(/[,;]+/).map(t=>t.trim()).filter(Boolean))];}
function saveForm(next){const h=$('#fHanzi').value.trim(),py=$('#fPy').value.trim(),tr=$('#fTr').value.trim(),tags=parseTags($('#fTags').value),comment=$('#fComment').value.trim();if(!h){alert('Введите слово.');return;}if(editingId){const w=words.find(x=>x.id===editingId);Object.assign(w,{hanzi:h,pinyin:py,translation:tr,tags,comment,kind:addKind,updatedAt:new Date().toISOString()});}else{const id=Math.max(0,...words.map(x=>+x.id||0))+1,order=Math.max(0,...words.map(x=>+x.order||0))+1;words.push({id,order,kind:addKind,hanzi:h,pinyin:py,translation:tr,tags,comment,laoshi:false,favorite:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}saveWords();if(next)renderAdd();else{kind=addKind;query='';tagFilter=[];filter='all';visible=120;renderWords();}}
function renderMore(){currentTab='more';setTabs();const sj=snapInfo();$('#content').innerHTML=`<div class="view-title">Ещё</div><div class="view-title" style="font-size:0;height:0;margin:0"></div><div class="settings-card"><div class="setting"><span>Всего записей</span><strong id="settingsCount"></strong></div>${KINDS.map(m=>`<div class="setting"><span>${m.ru} <span style="color:var(--muted)">${m.zh}</span></span><small>${countOf(m.k).toLocaleString('ru-RU')} · не в Лаоши: ${newOf(m.k).toLocaleString('ru-RU')}</small></div>`).join('')}</div><div class="settings-card"><button class="setting" id="tagManage"><span>Тэги словаря</span><small>${tagPool().length} шт. ›</small></button>${sj?`<button class="setting" id="snapRestore"><span>Автоснимок перед правками</span><small>${snapDate(sj.ts)} ›</small></button>`:''}</div><div class="settings-card"><button class="setting" id="exportCsv"><span>Экспорт для Excel</span><small>CSV ›</small></button><button class="setting" id="backup"><span>Резервная копия</span><small>JSON ›</small></button><button class="setting" id="restore"><span>Восстановить из копии</span><small>‹ JSON</small></button><input type="file" id="restoreFile" accept="application/json,.json" class="hidden"></div><div class="settings-card"><button class="setting" id="reset"><span>Вернуть исходный список из Excel</span><small>3913 слов</small></button></div><div class="settings-card"><div class="setting"><span>Мои слова</span><small>v${VERSION}</small></div></div>`;updateCounts();$('#tagManage').onclick=manageTags;const sr=$('#snapRestore');if(sr)sr.onclick=snapRestore;$('#exportCsv').onclick=exportCsv;$('#backup').onclick=backupJson;$('#restore').onclick=()=>$('#restoreFile').click();$('#restoreFile').onchange=restoreJson;$('#reset').onclick=resetBase;}
function showTags(){const pool=tagPool();$('#modal').innerHTML=`<div class="sheet"><div class="grab"></div><div class="sheet-title">Отбор по тэгам</div>${pool.length?pool.map(([t,n])=>`<button class="sortopt ${tagFilter.includes(t)?'on':''}" data-t="${esc(t)}">#${esc(t)} <span style="color:var(--muted);font-size:12px"> · ${n}</span></button>`).join(''):'<div class="empty">Тэгов пока нет</div>'}<div class="actions"><button class="secondary" id="tagClear">Сбросить отбор</button><button class="primary" id="tagDone" style="margin-top:0">Готово</button></div></div>`;$('#modal').classList.remove('hidden');$$('.sortopt[data-t]').forEach(b=>b.onclick=()=>{const t=b.dataset.t;tagFilter.includes(t)?tagFilter=tagFilter.filter(x=>x!==t):tagFilter.push(t);b.classList.toggle('on');});$('#tagClear').onclick=()=>{tagFilter=[];closeModal();visible=120;renderWords();};$('#tagDone').onclick=()=>{closeModal();visible=120;renderWords();};$('#modal').onclick=e=>{if(e.target.id==='modal')$('#tagDone').click();};}
function manageTags(){const pool=tagPool();$('#modal').innerHTML=`<div class="sheet"><div class="grab"></div><div class="sheet-title">Тэги словаря</div><div class="tagnote">Нажмите на тэг, чтобы переименовать. Крестик — удалить тэг у всех записей.</div>${pool.length?pool.map(([t,n])=>`<div class="tagrow"><button class="tagname" data-ren="${esc(t)}">#${esc(t)} <span style="color:var(--muted);font-size:12px">· ${n}</span></button><button class="tagdel" data-del="${esc(t)}" aria-label="Удалить тэг">✕</button></div>`).join(''):'<div class="empty">Тэгов пока нет</div>'}<div class="actions"><button class="primary" id="tagDone" style="margin-top:0">Готово</button></div></div>`;$('#modal').classList.remove('hidden');$$('[data-ren]').forEach(b=>b.onclick=()=>{const old=b.dataset.ren;const nv=prompt('Новое название тэга (пусто — удалить тэг):',old);if(nv===null)return;const t=nv.trim();snapMake('перед переименованием тэга');if(!t){words.forEach(w=>w.tags=(w.tags||[]).filter(x=>x!==old));}else{words.forEach(w=>{w.tags=(w.tags||[]).map(x=>x===old?t:x);});}tagFilter=tagFilter.map(x=>x===old?t:x).filter((x,i,a)=>x&&a.indexOf(x)===i);saveWords();manageTags();});$$('[data-del]').forEach(b=>b.onclick=()=>{const t=b.dataset.del;const n=(tagPool().find(x=>x[0]===t)||[t,0])[1];if(!confirm('Удалить тэг «'+t+'» у '+n+' записей?'))return;snapMake('перед удалением тэга «'+t+'»');words.forEach(w=>w.tags=(w.tags||[]).filter(x=>x!==t));tagFilter=tagFilter.filter(x=>x!==t);saveWords();manageTags();});$('#tagDone').onclick=()=>{closeModal();renderWords();};$('#modal').onclick=e=>{if(e.target.id==='modal')$('#tagDone').click();};}
function openDetail(id){const w=words.find(x=>x.id===id);if(!w)return;const k=KMAP[w.kind]||KMAP.word;$('#modal').innerHTML=`<div class="sheet"><div class="grab"></div><div class="detail-head"><button class="back" id="closeModal">Назад</button><span class="dkind">${k.ru} · ${k.zh}</span></div><div class="big-hanzi">${esc(w.hanzi)}</div><div class="big-py">${esc(w.pinyin||'')}</div><div class="big-tr">${esc(w.translation||'')}</div><div class="info"><div class="k">Тэги</div><div class="tagline">${(w.tags||[]).length?(w.tags||[]).map(t=>`<span class="tg">#${esc(t)} <button class="tgx" data-rm="${esc(t)}" aria-label="Убрать">✕</button></span>`).join(''):'<span class="muted">пока нет</span>'}</div><div class="tagadd"><input id="newTag" placeholder="новый тэг" autocomplete="off" list="tagList"><button class="small-btn" id="addTag">Добавить</button></div></div>${w.comment?`<div class="info"><div class="k">Заметка</div>${esc(w.comment)}</div>`:''}<div class="info"><div class="k">Статус</div>${w.laoshi?'Уже в Лаоши ✓':'Ещё не внесено в Лаоши'}</div><div class="info"><div class="k">Порядок в словаре</div>№ ${w.order}</div><datalist id="tagList">${tagPool().map(t=>`<option value="${esc(t[0])}"></option>`).join('')}</datalist><div class="actions"><button class="primary" id="laoshiBtn" style="margin-top:0">${w.laoshi?'Снять отметку «в Лаоши»':'✓ Внести в Лаоши'}</button><button class="secondary" id="editWord" style="margin-top:0">Редактировать</button><button class="danger" id="deleteWord">Удалить</button></div></div>`;$('#modal').classList.remove('hidden');$('#closeModal').onclick=closeModal;$('#laoshiBtn').onclick=()=>toggleLaoshi(id);$('#editWord').onclick=()=>{closeModal();renderAdd(id);};$('#addTag').onclick=()=>{const t=$('#newTag').value.trim();if(!t)return;const add=parseTags(t);add.forEach(x=>{if(!(w.tags||[]).includes(x))w.tags.push(x);});w.updatedAt=new Date().toISOString();saveWords();openDetail(id);};$$('[data-rm]').forEach(b=>b.onclick=()=>{const t=b.dataset.rm;w.tags=(w.tags||[]).filter(x=>x!==t);w.updatedAt=new Date().toISOString();saveWords();openDetail(id);});$('#deleteWord').onclick=()=>{const nm=w.hanzi;if(confirm('Удалить «'+nm+'»?')){snapMake('перед удалением «'+nm+'»');const before=words.slice();words=words.filter(x=>x.id!==id);saveWords();closeModal();renderWords();toast('Удалено: '+nm,'Вернуть',()=>{words=before;saveWords();renderWords();},'Восстановлено: '+nm);}};}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML='';}
function showSort(){$('#modal').innerHTML=`<div class="sheet"><div class="grab"></div><div class="sheet-title">Сортировка</div><button class="sortopt ${sortMode==='order'?'on':''}" data-sort="order">По мере добавления — основной</button><button class="sortopt ${sortMode==='new'?'on':''}" data-sort="new">Последние добавленные сверху</button><button class="sortopt ${sortMode==='hanzi'?'on':''}" data-sort="hanzi">По китайскому алфавиту</button></div>`;$('#modal').classList.remove('hidden');$$('.sortopt').forEach(b=>b.onclick=()=>{sortMode=b.dataset.sort;closeModal();visible=120;renderList();});$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal();};}
function dl(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function csvCell(s){s=String(s??'');return /[",\r\n;]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function exportCsv(){const rows=[['№','раздел','слово','pinyin','перевод','тэги','в Лаоши','заметка']];words.slice().sort((a,b)=>(a.order||0)-(b.order||0)).forEach(w=>rows.push([w.order,(KMAP[w.kind]||KMAP.word).ru,w.hanzi,w.pinyin,w.translation,(w.tags||[]).join(', '),w.laoshi?'да':'',w.comment]));dl('cidian-'+new Date().toISOString().slice(0,10)+'.csv','﻿'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
function backupJson(){dl('cidian-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({version:VERSION,words},null,2),'application/json');}
function restoreJson(e){const f=e.target.files&&e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const j=JSON.parse(r.result);const a=Array.isArray(j)?j:j.words;if(!Array.isArray(a)||!a.length)throw 0;if(confirm('Заменить текущий словарь данными из резервной копии?')){snapMake('перед восстановлением из файла');words=a.map(migrate);saveWords();renderMore();}}catch(_){alert('Не удалось прочитать резервную копию.');}};r.readAsText(f);}
function resetBase(){if(confirm('Вернуть исходные 3913 слов из первого листа Excel? Все локальные изменения (тэги и отметки Лаоши) будут удалены.')){snapMake('перед возвратом исходного списка');words=BASE_WORDS.map(x=>({...x}));saveWords();renderMore();}}
$$('.tab').forEach(b=>b.onclick=()=>{const t=b.dataset.tab;if(t==='words')renderWords();if(t==='add')renderAdd();if(t==='more')renderMore();});
$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal();};
renderWords();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js?v=2.1.0',{updateViaCache:'none'}).catch(()=>{});
