const BASE_WORDS=(window.CIDIAN_BASE||[]).map((r,i)=>({id:i+1,order:i+1,hanzi:r[0]||'',pinyin:r[1]||'',translation:r[2]||'',note:r[3]||'',comment:'',favorite:false,createdAt:'',updatedAt:''}));
const STORAGE='cidian-data-v1', VERSION='1.1.1';
let words=loadWords(), currentTab='words', sortMode='order', filter='all', query='', visible=120, editingId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function loadWords(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');if(Array.isArray(x)&&x.length)return x;}catch(e){}return BASE_WORDS.map(x=>({...x}));}
function saveWords(){try{localStorage.setItem(STORAGE,JSON.stringify(words));}catch(e){alert('Не удалось сохранить словарь на устройстве.');}updateCount();}
function updateCount(){const el=$('#count');if(el)el.textContent=words.length.toLocaleString('ru-RU')+' слов'; const sc=$('#settingsCount'); if(sc)sc.textContent=words.length.toLocaleString('ru-RU');}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function getFiltered(){let a=words.slice();const q=norm(query.trim());if(q)a=a.filter(w=>norm(w.hanzi+' '+w.pinyin+' '+w.translation+' '+w.note+' '+w.comment).includes(q));if(filter==='fav')a=a.filter(w=>w.favorite);if(filter==='note')a=a.filter(w=>w.note);if(sortMode==='order')a.sort((a,b)=>(a.order||0)-(b.order||0));if(sortMode==='new')a.sort((a,b)=>(b.order||0)-(a.order||0));if(sortMode==='hanzi')a.sort((a,b)=>String(a.hanzi).localeCompare(String(b.hanzi),'zh-CN'));return a;}
function renderWords(){currentTab='words';setTabs();$('#content').innerHTML=`<div class="head"><img src="icon-192-v3.png" class="app-icon" alt="词 — Мои слова" width="96" height="96"><div class="headtext"><div class="title">Мои слова</div><div class="subtitle">我的生词</div><div class="count" id="count"></div></div></div><div class="searchrow"><div class="search"><span class="mag">⌕</span><input id="q" placeholder="Поиск по слову, пиньиню или переводу" value="${esc(query)}"><button class="clear ${query?'':'hidden'}" id="clearQ" aria-label="Очистить поиск">×</button></div><button class="iconbtn" id="sortBtn" aria-label="Сортировка">☷</button></div><div class="chips"><button class="chip ${filter==='all'?'on':''}" data-f="all">Все</button><button class="chip ${filter==='fav'?'on':''}" data-f="fav">Избранные</button><button class="chip ${filter==='note'?'on':''}" data-f="note">С пометками</button></div><div class="list" id="list"></div>`;updateCount();bindWordControls();renderList();}
function bindWordControls(){$('#q').addEventListener('input',e=>{query=e.target.value;visible=120;$('#clearQ').classList.toggle('hidden',!query);renderList();});$('#clearQ').onclick=()=>{query='';$('#q').value='';$('#clearQ').classList.add('hidden');visible=120;renderList();};$('#sortBtn').onclick=showSort;$$('.chip').forEach(b=>b.onclick=()=>{filter=b.dataset.f;visible=120;$$('.chip').forEach(x=>x.classList.toggle('on',x.dataset.f===filter));renderList();});}
function renderList(){const all=getFiltered(), take=all.slice(0,visible);const list=$('#list');if(!list)return;if(!take.length){list.innerHTML='<div class="empty">Ничего не найдено</div>';return;}list.innerHTML=take.map(w=>`<div class="word" data-id="${w.id}"><div class="hanzi">${esc(w.hanzi)}</div><div class="meta"><div class="py">${esc(w.pinyin||'')}</div><div class="tr">${esc(w.translation||'')}</div>${w.note?`<span class="note">${esc(w.note)}</span>`:''}</div><button class="star ${w.favorite?'on':''}" data-star="${w.id}">${w.favorite?'★':'☆'}</button></div>`).join('')+(all.length>visible?`<button class="more" id="more">Показать ещё · ${all.length-visible}</button>`:'');list.querySelectorAll('.word').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-star]'))return;openDetail(+el.dataset.id);});list.querySelectorAll('[data-star]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(+b.dataset.star);});const m=$('#more');if(m)m.onclick=()=>{visible+=150;renderList();};}
function toggleFav(id){const w=words.find(x=>x.id===id);if(!w)return;w.favorite=!w.favorite;w.updatedAt=new Date().toISOString();saveWords();renderList();}
function setTabs(){$$('.tab').forEach(x=>x.classList.toggle('on',x.dataset.tab===currentTab));$('#fab').classList.toggle('hidden',currentTab!=='words');}
function renderAdd(id=null){currentTab='add';editingId=id;setTabs();const w=id?words.find(x=>x.id===id):{hanzi:'',pinyin:'',translation:'',note:'',comment:''};$('#content').innerHTML=`<div class="view-title">${id?'Редактировать':'Добавить слово'}</div><div class="subtitle" style="margin-top:-15px;margin-bottom:20px">${id?'编辑词语':'新的词语'}</div><div class="form"><label>Слово</label><input id="fHanzi" value="${esc(w.hanzi)}" autocomplete="off"><label>Пиньинь</label><input id="fPy" value="${esc(w.pinyin)}" autocomplete="off"><label>Перевод</label><textarea id="fTr">${esc(w.translation)}</textarea><label>Пометка</label><input id="fNote" value="${esc(w.note)}" placeholder="необязательно"><label>Комментарий</label><textarea id="fComment" placeholder="необязательно">${esc(w.comment||'')}</textarea><button class="primary" id="saveBtn">Сохранить</button>${id?'':'<button class="secondary" id="saveNext">Сохранить и добавить следующее</button>'}</div>`;$('#saveBtn').onclick=()=>saveForm(false);const sn=$('#saveNext');if(sn)sn.onclick=()=>saveForm(true);}
function saveForm(next){const h=$('#fHanzi').value.trim(),py=$('#fPy').value.trim(),tr=$('#fTr').value.trim(),note=$('#fNote').value.trim(),comment=$('#fComment').value.trim();if(!h){alert('Введите слово.');return;}if(editingId){const w=words.find(x=>x.id===editingId);Object.assign(w,{hanzi:h,pinyin:py,translation:tr,note,comment,updatedAt:new Date().toISOString()});}else{const id=Math.max(0,...words.map(x=>+x.id||0))+1,order=Math.max(0,...words.map(x=>+x.order||0))+1;words.push({id,order,hanzi:h,pinyin:py,translation:tr,note,comment,favorite:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}saveWords();if(next)renderAdd();else renderWords();}
function renderMore(){currentTab='more';setTabs();$('#content').innerHTML=`<div class="view-title">Ещё</div><div class="settings-card"><div class="setting"><span>Количество слов</span><strong id="settingsCount"></strong></div><button class="setting" id="exportCsv"><span>Экспорт для Excel</span><small>CSV ›</small></button><button class="setting" id="backup"><span>Резервная копия</span><small>JSON ›</small></button><button class="setting" id="restore"><span>Восстановить из копии</span><small>‹ JSON</small></button><input type="file" id="restoreFile" accept="application/json,.json" class="hidden"></div><div class="settings-card"><button class="setting" id="reset"><span>Вернуть исходный список из Excel</span><small>3913 слов</small></button></div><div class="settings-card"><div class="setting"><span>Мои слова</span><small>v${VERSION}</small></div><div class="setting"><span>Порядок по умолчанию</span><small>по мере добавления</small></div></div>`;updateCount();$('#exportCsv').onclick=exportCsv;$('#backup').onclick=backupJson;$('#restore').onclick=()=>$('#restoreFile').click();$('#restoreFile').onchange=restoreJson;$('#reset').onclick=resetBase;}
function openDetail(id){const w=words.find(x=>x.id===id);if(!w)return;$('#modal').innerHTML=`<div class="sheet"><div class="grab"></div><div class="detail-head"><button class="back" id="closeModal">Назад</button><button class="star ${w.favorite?'on':''}" id="detailStar">${w.favorite?'★':'☆'}</button></div><div class="big-hanzi">${esc(w.hanzi)}</div><div class="big-py">${esc(w.pinyin||'')}</div><div class="big-tr">${esc(w.translation||'')}</div>${w.note?`<div class="info"><div class="k">Пометка</div>${esc(w.note)}</div>`:''}${w.comment?`<div class="info"><div class="k">Комментарий</div>${esc(w.comment)}</div>`:''}<div class="info"><div class="k">Порядок в словаре</div>№ ${w.order}</div><div class="actions"><button class="primary" id="editWord" style="margin-top:0">Редактировать</button><button class="danger" id="deleteWord">Удалить</button></div></div>`;$('#modal').classList.remove('hidden');$('#closeModal').onclick=closeModal;$('#detailStar').onclick=()=>{toggleFav(id);openDetail(id);};$('#editWord').onclick=()=>{closeModal();renderAdd(id);};$('#deleteWord').onclick=()=>{if(confirm('Удалить слово «'+w.hanzi+'»?')){words=words.filter(x=>x.id!==id);saveWords();closeModal();renderWords();}};}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML='';}
function showSort(){$('#modal').innerHTML=`<div class="sheet"><div class="grab"></div><div class="sheet-title">Сортировка</div><button class="sortopt ${sortMode==='order'?'on':''}" data-sort="order">По мере добавления — основной</button><button class="sortopt ${sortMode==='new'?'on':''}" data-sort="new">Последние добавленные сверху</button><button class="sortopt ${sortMode==='hanzi'?'on':''}" data-sort="hanzi">По китайскому алфавиту</button></div>`;$('#modal').classList.remove('hidden');$$('.sortopt').forEach(b=>b.onclick=()=>{sortMode=b.dataset.sort;closeModal();visible=120;renderList();});$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal();};}
function dl(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function csvCell(s){s=String(s??'');return /[",\r\n;]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function exportCsv(){const rows=[['№','слово','pinyin','перевод','пометка','комментарий']];words.slice().sort((a,b)=>a.order-b.order).forEach(w=>rows.push([w.order,w.hanzi,w.pinyin,w.translation,w.note,w.comment]));dl('cidian-'+new Date().toISOString().slice(0,10)+'.csv','﻿'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
function backupJson(){dl('cidian-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({version:VERSION,words},null,2),'application/json');}
function restoreJson(e){const f=e.target.files&&e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const j=JSON.parse(r.result);const a=Array.isArray(j)?j:j.words;if(!Array.isArray(a)||!a.length)throw 0;if(confirm('Заменить текущий словарь данными из резервной копии?')){words=a;saveWords();renderMore();}}catch(_){alert('Не удалось прочитать резервную копию.');}};r.readAsText(f);}
function resetBase(){if(confirm('Вернуть исходные 3913 слов из первого листа Excel? Все локальные изменения будут удалены.')){words=BASE_WORDS.map(x=>({...x}));saveWords();renderMore();}}
$$('.tab').forEach(b=>b.onclick=()=>{const t=b.dataset.tab;if(t==='words')renderWords();if(t==='add')renderAdd();if(t==='more')renderMore();});$('#fab').onclick=()=>renderAdd();$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal();};
renderWords();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js?v=1.1.1',{updateViaCache:'none'}).catch(()=>{});